Typescript
KristinaRev/React-Kanban-Board pull request #1
Opened 2024-05-28 11:47 UTC by KristinaRev

2024-05-28 12:40 UTC, igorevichfromspb commented on src/components/footer/Footer.tsx
> +import React from 'react';
Вот этот импорт можно не писать в каждом компоненте

2024-05-28 12:41 UTC, igorevichfromspb commented on src/components/footer/Footer.tsx
> +const Footer: React.FC<FooterProps> = ({ backlogCount, doneCount, inProgressCount, readyCount }) => {
Здесь, соответственно, будет просто FC

2024-05-28 12:41 UTC, igorevichfromspb commented on src/components/footer/Footer.tsx
> +export default React.memo(observer(Footer));
Здесь просто memo

2024-05-28 12:52 UTC, igorevichfromspb commented on src/components/forms/FormAddNewTask.tsx
> +	const [showPrompt, setShowPrompt] = useState(false);
Хуки тоже лучше типизировать

2024-05-28 12:58 UTC, igorevichfromspb commented on src/components/forms/FormAddNewTask.tsx
> +		label: list as string,
`as` старайся использовать только в крайних случаях, это не самая лучшая практика

2024-05-28 12:59 UTC, igorevichfromspb commented on src/components/list/List.tsx
> +interface Props {
ListProps

2024-05-28 13:03 UTC, igorevichfromspb commented on src/components/list/List.tsx
> +		drop: (item) => moveTask((item as { id: string }).id, type),
Здесь тоже от `as` можно избавиться

2024-05-28 13:07 UTC, igorevichfromspb requested changes
Из критических моментов только использование `as`, постарайся избавится от него, если не получится, то я помогу
Остальные замечания - придирки

2024-05-28 13:13 UTC, KristinaRev commented on src/components/footer/Footer.tsx
> +export default React.memo(observer(Footer));
а будет ли мобикс без этого работать?

2024-05-28 13:21 UTC, igorevichfromspb commented on src/components/footer/Footer.tsx
> +export default React.memo(observer(Footer));
А почему нет?
Импортируй `memo `из "react"

2024-05-29 11:44 UTC, igorevichfromspb commented on src/declarations.d.ts
> +}
А тут недостаточно будет просто установить типы для это библиотеки?
`npm install --save @types/uniqid`

2024-05-29 11:47 UTC, igorevichfromspb approved these changes

2024-06-03 09:31 UTC, igorevichfromspb commented on src/ui/select/Select.jsx
> +                    <option key={`${option.value}-${index}`} value={option.value}>
Почему в качестве ключа просто не используешь `option.value`?

2024-06-03 09:36 UTC, igorevichfromspb commented on src/components/Login/Login.tsx
> +    user: any;
Про `any` забудь

2024-06-03 09:42 UTC, igorevichfromspb commented on src/components/Login/Login.tsx
> +            <div className={`$""icon} ${isMounted ? "isopen" : ''}`} />
Тут явно с кавычками проблема

2024-06-03 09:45 UTC, igorevichfromspb commented on src/components/Login/Login.tsx
> +function useDelayUnmount(isMounted: boolean, delayTime: number): boolean {
Этот хук можно вынести в папку hooks, если он не привязан конкретно к компоненту `Login`

2024-06-04 09:49 UTC, KrisKipper commented on src/ui/select/Select.jsx
> +                    <option key={`${option.value}-${index}`} value={option.value}>
там ошибка лезла, что-то как раз на счет ключа, изменила и всё ок о_О

2024-06-04 10:11 UTC, KrisKipper commented on src/ui/select/Select.jsx
> +                    <option key={`${option.value}-${index}`} value={option.value}>
о, сейчас убрала это и все равно все нормально, значит и без этого норм было)

2024-06-04 10:28 UTC, merged